---
- hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy website files
      copy:
        src: /"C:\Users\pc\Downloads\monsite.zip"
        dest: /var/www/html/

    - name: Unzip website files
      command: unzip /var/www/html/monsite.zip -d /var/www/html/
