groups:
  - name: example
    rules:
      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes / node_filesystem_size_bytes * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space is running low ({{ $value }}%) on instance {{ $labels.instance }}"
          description: "Disk space is running low ({{ $value }}%) on instance {{ $labels.instance }}."
